source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!

workspace 'BoostlingoSdk.xcworkspace'

target 'BoostlingoSdk' do
  project 'BoostlingoSdk.xcodeproj'
  pod 'BoostlingoSDK', '0.5.10'
end

